project:
  type: website
  output-dir: docs

website:
  title: ""
  favicon: _extra/_images/favicon_2.ico
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-523-SU25/final-project-Herling-Mi
    left:
      - href: "#"
        text: "<img src='_extra/_images/head_phones.png' style='height: 28px; transform: scale(3.5); margin-right: 12px; vertical-align: middle;'/>"
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    css: _extra/_css/styles.css   # 👈 Add this line

execute:
  freeze: auto
